<img src=https://omes-va.com/wp-content/uploads/2021/06/33_puntos_referencia.jpeg>

Puntos de referencia en el cuerpo para mediapipe

In [ ]:
ALGORITMO PARA USAR CON FOTOS , OPCIÓN ES LA PREDETERMINADA 

In [ ]:
import cv2
import mediapipe as mp


mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose

with mp_pose.Pose(
    static_image_mode=True) as pose:   #PARA VIDEOS PONER FALSE /TRUE ES PARA FOTOS
    image = cv2.imread("data/dataset_train/IMG_5620(1)_033.jpg")
    image = cv2.resize(src = image, dsize = (771,1370))
    height, width , _ = image.shape
    image_rgb = cv2.cvtColor(image,cv2.COLOR_BGR2RGB)

    results = pose.process(image_rgb)
    print ("Pose landmarks:", results.pose_landmarks)

    if results.pose_landmarks is not None:
        mp_drawing.draw_landmarks(image, results.pose_landmarks,
            mp_pose.POSE_CONNECTIONS,
            mp_drawing.DrawingSpec(color=(43,214,38), thickness = 2, circle_radius= 3),   #personalizar el esqueleto
            mp_drawing.DrawingSpec(color = (255,255,255), thickness = 2))

    cv2.imshow("Image", image)
    cv2.waitKey(0)
cv2.destroyAllWindows()


ALGORITMO PARA USAR CON FOTOS , OPCIÓN PERSONALIZADA PARA NUESTRO PROYECTO

In [ ]:
#para fotos detecta el esqueleto (sin puntos de la cara, ni manos o pies), en caso de que la cadera quede paralela
#a la rodilla con oscilación de 30 puntos ; por personalizar letras colores etc
# esta opción solo trabaja para este tipo

import cv2
import mediapipe as mp
import matplotlib.pyplot as plt

from utils import draw_text


mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose

with mp_pose.Pose(
    static_image_mode=True) as pose:   #PARA VIDEOS PONER FALSE /TRUE ES PARA FOTOS
    image = cv2.imread("data/dataset_train/IMG_5615_012.jpg")
    image = cv2.resize(src = image, dsize = (642,1141))
    height, width , _ = image.shape
    image_rgb = cv2.cvtColor(image,cv2.COLOR_BGR2RGB)

    results = pose.process(image_rgb)
    #print ("Pose landmarks:", results.pose_landmarks)

    if results.pose_landmarks is not None:
        print(int(results.pose_landmarks.landmark[mp_pose.PoseLandmark.RIGHT_SHOULDER].z)) #saca la coordenada del hombro derecho, medida en cm se multiplica por el ancho para sacar la medida en pixeles 
        x11= int(results.pose_landmarks.landmark[11].x * width)
        y11 = int(results.pose_landmarks.landmark[11].y * height)

        x12= int(results.pose_landmarks.landmark[12].x * width)
        y12= int(results.pose_landmarks.landmark[12].y * height)

        x13= int(results.pose_landmarks.landmark[13].x * width)
        y13 = int(results.pose_landmarks.landmark[13].y * height)

        x14= int(results.pose_landmarks.landmark[14].x * width)
        y14 = int(results.pose_landmarks.landmark[14].y * height)

        x15= int(results.pose_landmarks.landmark[15].x * width)
        y15 = int(results.pose_landmarks.landmark[15].y * height)

        x16= int(results.pose_landmarks.landmark[16].x * width)
        y16 = int(results.pose_landmarks.landmark[16].y * height)

        #x17= int(results.pose_landmarks.landmark[17].x * width)
        #y17= int(results.pose_landmarks.landmark[17].y * height)

        #x18= int(results.pose_landmarks.landmark[18].x * width)
        #y18= int(results.pose_landmarks.landmark[18].y * height)

        #x19= int(results.pose_landmarks.landmark[19].x * width)
        #y19= int(results.pose_landmarks.landmark[19].y * height)

        #x20= int(results.pose_landmarks.landmark[20].x * width)
        #y20= int(results.pose_landmarks.landmark[20].y * height)

        #x21= int(results.pose_landmarks.landmark[21].x * width)
        #y21= int(results.pose_landmarks.landmark[21].y * height)

        #x22= int(results.pose_landmarks.landmark[22].x * width)
        #y22= int(results.pose_landmarks.landmark[22].y * height)

        x23= int(results.pose_landmarks.landmark[23].x * width)
        y23= int(results.pose_landmarks.landmark[23].y * height)

        x24= int(results.pose_landmarks.landmark[24].x * width)
        y24= int(results.pose_landmarks.landmark[24].y * height)

        x25= int(results.pose_landmarks.landmark[25].x * width)
        y25= int(results.pose_landmarks.landmark[25].y * height)

        x26= int(results.pose_landmarks.landmark[26].x * width)
        y26= int(results.pose_landmarks.landmark[26].y * height)

        x27= int(results.pose_landmarks.landmark[27].x * width)
        y27 = int(results.pose_landmarks.landmark[27].y * height)

        x28= int(results.pose_landmarks.landmark[28].x * width)
        y28= int(results.pose_landmarks.landmark[28].y * height)

        puntuacion = list()

        






      
        print (x24, y24, x26 , y26, x23, y23, x25, y25, x27, y27)
        cv2.line(image, ( x11, y11), (x12 , y12), (255 , 255 , 255), 3) #unión de punto xy1 con xy2
        cv2.line(image, ( x11, y11), (x13 , y13), (255 , 255 , 255), 3)
        cv2.line(image, ( x11, y11), (x23 , y23), (255 , 255 , 255), 3) #unión de punto xy2 con xy3
        cv2.line(image, ( x13, y13), (x15 , y15), (255 , 255 , 255), 3) 
        cv2.line(image, ( x12, y12), (x14 , y14), (255 , 255 , 255), 3)
        cv2.line(image, ( x14, y14), (x16 , y16), (255 , 255 , 255), 3) 
        cv2.line(image, ( x12, y12), (x24 , y24), (255 , 255 , 255), 3)
        cv2.line(image, ( x24, y24), (x26 , y26), (255 , 255 , 255), 3) 
        cv2.line(image, ( x24, y24), (x23 , y23), (255 , 255 , 255), 3)
        cv2.line(image, ( x26, y26), (x28 , y28), (255 , 255 , 255), 3) 
        cv2.line(image, ( x23, y23), (x25 , y25), (255 , 255 , 255), 3)
        cv2.line(image, ( x25, y25), (x27 , y27), (255 , 255 , 255), 3) 
        


        cv2.circle(image,(x11, y11), 6, (43,214,38), -1) #color verde
        cv2.circle(image,(x12, y12), 6, (43,214,38), -1) #color verde
        cv2.circle(image,(x13, y13), 6, (43,214,38), -1) #color verde
        cv2.circle(image,(x15, y15), 6, (43,214,38), -1) #color verde
        cv2.circle(image,(x14, y14), 6, (43,214,38), -1) #color verde
        cv2.circle(image,(x16, y16), 6, (43,214,38), -1) #color verde
        cv2.circle(image,(x24, y24), 6, (43,214,38), -1) #color verde
        cv2.circle(image,(x26, y26), 6, (43,214,38), -1) #color verde
        cv2.circle(image,(x28, y28), 6, (43,214,38), -1) #color verde
        cv2.circle(image,(x23, y23), 6, (43,214,38), -1) #color azul corrdenadas según indice del dibujo
        cv2.circle(image,(x25, y25), 6, (43,214,38), -1) #color azul corrdenadas según indice del dibujo
        cv2.circle(image,(x27, y27), 6, (43,214,38), -1)

        if  y24 >= y26-30 and y24 <=y26+30 and y23 >= y25-30 and y23 <=y25+30  :
                    cv2.line(image, ( x24, y24), (x26 , y26), (0 , 255 , 255), 3) #unión de punto xy1 con xy2
                    cv2.line(image, ( x23, y23), (x25 , y25), (0 , 255 , 255), 3) #unión de punto xy1 con xy2
                    
                    puntos = 2
                    puntuacion.append(puntos)
                    print (f" puntuación: {sum(puntuacion)} ")

                    if sum(puntuacion) >= 2 :

                        font = cv2.FONT_HERSHEY_SIMPLEX

                        # cv2.putText(img = image, 
                        #             text = "GOOD JOB",
                        #             org = (200, 200),
                        #             fontFace = font,
                        #             fontScale = 2,
                        #             color = (255, 255, 255),
                        #             thickness = 2,
                        #             lineType = cv2.LINE_AA)
                        draw_text(
                            image, 
                            'GOOD JOB', 
                            pos=(30, 80),
                            text_color=(0, 0, 0),
                            font_scale=1,
                            text_color_bg=(37, 190, 38)
                        )  

                    plt.imshow(image)
                    plt.show()

        #mp_drawing.draw_landmarks(image, results.pose_landmarks,
        #   mp_pose.POSE_CONNECTIONS,
        #   mp_drawing.DrawingSpec(color=(43,214,38), thickness = 2, circle_radius= 3),   #personalizar el esqueleto
        #  mp_drawing.DrawingSpec(color = (255,255,255), thickness = 2))

    cv2.imshow("Image", image)
    cv2.waitKey(0)
cv2.destroyAllWindows()




PARA HACERLO CON VIDEO 


ALGORITMO PARA USAR CON VÍDEO , OPCIÓN ES LA PREDETERMINADA 

ALGORITMO PARA USAR CON VÍDEO , OPCIÓN PERSONALIZADA PARA NUESTRO PROYECTO

In [ ]:
#con video 

#con video 

import cv2
import mediapipe as mp
import matplotlib.pyplot as plt


mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose

cap = cv2.VideoCapture("C:/Users/esuns/Downloads/dataset_train-20240610T183045Z-001/dataset_train/WIN_20240624_02_50_52_Pro.mp4")


with mp_pose.Pose(
    static_image_mode=False) as pose:   #PARA VIDEOS PONER FALSE /TRUE ES PARA FOTOS
        while True:
             ret, frame = cap.read()
             if ret == False:
                  break
             heigth, width, _ = frame.shape 
             frame_rgb= cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
             results = pose.process(frame_rgb)

             if results.pose_landmarks is not None:
               print(int(results.pose_landmarks.landmark[mp_pose.PoseLandmark.RIGHT_SHOULDER].z)) #saca la coordenada del hombro derecho, medida en cm se multiplica por el ancho para sacar la medida en pixeles 
               x11= int(results.pose_landmarks.landmark[11].x * width)
               y11 = int(results.pose_landmarks.landmark[11].y * heigth)

               x12= int(results.pose_landmarks.landmark[12].x * width)
               y12= int(results.pose_landmarks.landmark[12].y * heigth)

               x13= int(results.pose_landmarks.landmark[13].x * width)
               y13 = int(results.pose_landmarks.landmark[13].y * heigth)

               x14= int(results.pose_landmarks.landmark[14].x * width)
               y14 = int(results.pose_landmarks.landmark[14].y * heigth)

               x15= int(results.pose_landmarks.landmark[15].x * width)
               y15 = int(results.pose_landmarks.landmark[15].y * heigth)

               x16= int(results.pose_landmarks.landmark[16].x * width)
               y16 = int(results.pose_landmarks.landmark[16].y * heigth)

               #x17= int(results.pose_landmarks.landmark[17].x * width)
               #y17= int(results.pose_landmarks.landmark[17].y * height)

               #x18= int(results.pose_landmarks.landmark[18].x * width)
               #y18= int(results.pose_landmarks.landmark[18].y * height)

               #x19= int(results.pose_landmarks.landmark[19].x * width)
               #y19= int(results.pose_landmarks.landmark[19].y * height)

               #x20= int(results.pose_landmarks.landmark[20].x * width)
               #y20= int(results.pose_landmarks.landmark[20].y * height)

               #x21= int(results.pose_landmarks.landmark[21].x * width)
               #y21= int(results.pose_landmarks.landmark[21].y * height)

               #x22= int(results.pose_landmarks.landmark[22].x * width)
               #y22= int(results.pose_landmarks.landmark[22].y * height)

               x23= int(results.pose_landmarks.landmark[23].x * width)
               y23= int(results.pose_landmarks.landmark[23].y * heigth)

               x24= int(results.pose_landmarks.landmark[24].x * width)
               y24= int(results.pose_landmarks.landmark[24].y * heigth)

               x25= int(results.pose_landmarks.landmark[25].x * width)
               y25= int(results.pose_landmarks.landmark[25].y * heigth)

               x26= int(results.pose_landmarks.landmark[26].x * width)
               y26= int(results.pose_landmarks.landmark[26].y * heigth)

               x27= int(results.pose_landmarks.landmark[27].x * width)
               y27 = int(results.pose_landmarks.landmark[27].y * heigth)

               x28= int(results.pose_landmarks.landmark[28].x * width)
               y28= int(results.pose_landmarks.landmark[28].y * heigth)

               puntuacion = list()

               






               
               print (x24, y24, x26 , y26, x23, y23, x25, y25, x27, y27)
               cv2.line(frame, ( x11, y11), (x12 , y12), (255 , 255 , 255), 3) #unión de punto xy1 con xy2
               cv2.line(frame, ( x11, y11), (x13 , y13), (255 , 255 , 255), 3)
               cv2.line(frame, ( x11, y11), (x23 , y23), (255 , 255 , 255), 3) #unión de punto xy2 con xy3
               cv2.line(frame, ( x13, y13), (x15 , y15), (255 , 255 , 255), 3) 
               cv2.line(frame, ( x12, y12), (x14 , y14), (255 , 255 , 255), 3)
               cv2.line(frame, ( x14, y14), (x16 , y16), (255 , 255 , 255), 3) 
               cv2.line(frame, ( x12, y12), (x24 , y24), (255 , 255 , 255), 3)
               cv2.line(frame, ( x24, y24), (x26 , y26), (255 , 255 , 255), 3) 
               cv2.line(frame, ( x24, y24), (x23 , y23), (255 , 255 , 255), 3)
               cv2.line(frame, ( x26, y26), (x28 , y28), (255 , 255 , 255), 3) 
               cv2.line(frame, ( x23, y23), (x25 , y25), (255 , 255 , 255), 3)
               cv2.line(frame, ( x25, y25), (x27 , y27), (255 , 255 , 255), 3) 
               


               cv2.circle(frame,(x11, y11), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x12, y12), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x13, y13), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x15, y15), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x14, y14), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x16, y16), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x24, y24), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x26, y26), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x28, y28), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x23, y23), 6, (43,214,38), -1) #color azul corrdenadas según indice del dibujo
               cv2.circle(frame,(x25, y25), 6, (43,214,38), -1) #color azul corrdenadas según indice del dibujo
               cv2.circle(frame,(x27, y27), 6, (43,214,38), -1)

               if  y24 >= y26-30 and y24 <=y26+30 and y23 >= y25-30 and y23 <=y25+30  :
                    cv2.line(frame, ( x24, y24), (x26 , y26), (0 , 255 , 255), 3) #unión de punto xy1 con xy2
                    cv2.line(frame, ( x23, y23), (x25 , y25), (0 , 255 , 255), 3) #unión de punto xy1 con xy2
                              
                    puntos = 2
                    puntuacion.append(puntos)
                    print (f" puntuación: {sum(puntuacion)} ")

               if sum(puntuacion) >= 2 :

                    font = cv2.FONT_HERSHEY_SIMPLEX

                    cv2.putText(img = frame, 
                                                       text = "GOOD JOB",
                                                       org = (200, 200),
                                                       fontFace = font,
                                                       fontScale = 2,
                                                       color = (255, 255, 255),
                                                       thickness = 2,
                                                       lineType = cv2.LINE_AA)

                    plt.imshow(frame)
                    plt.show()


          
             
               cv2.imshow("Frame", frame)
               if cv2.waitKey(1) & 0xFF == 27:
                    break
             
cap.release()
cv2.destroyAllWindows()

ALGORITMO PARA USAR CON STREAMING, OPCIÓN PREDETERMINADA

In [ ]:
#con video streaming

import cv2
import mediapipe as mp


mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose

cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)


with mp_pose.Pose(
    static_image_mode=False) as pose:   #PARA VIDEOS PONER FALSE /TRUE ES PARA FOTOS
        while True:
             ret, frame = cap.read()
             if ret == False:
                  break
             frame = cv2.flip(frame,1)  #espejo a la camara 
             heigth, width, _ = frame.shape 
             frame_rgb= cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
             results = pose.process(frame_rgb)

             if results.pose_landmarks is not None:
               mp_drawing.draw_landmarks(
                    frame, results.pose_landmarks,
                    mp_pose.POSE_CONNECTIONS,
                    mp_drawing.DrawingSpec(color=(43,214,38), thickness = 2, circle_radius= 3),   #personalizar el esqueleto
                    mp_drawing.DrawingSpec(color = (255,255,255), thickness = 2))
               print(frame.shape)
          
             
             cv2.imshow("Frame", frame)
             if cv2.waitKey(1) & 0xFF == 27:
                  break
             
cap.release()
cv2.destroyAllWindows()

In [ ]:

import cv2
import mediapipe as mp
cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)
#cap.read()
ret, frame = cap.read()
cv2.imshow("Frame", frame)
cap.release()
#cv2.destroyAllWindows()

In [ ]:
ALGORITMO PARA USAR CON STREAMING, OPCIÓN PERSONALIZADA PARA NUESTRO PROYECTO

In [ ]:
import cv2
import mediapipe as mp
import matplotlib.pyplot as plt


mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose

cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)

puntuacion= list()
with mp_pose.Pose(
    static_image_mode=False) as pose:   #PARA VIDEOS PONER FALSE /TRUE ES PARA FOTOS
        while True:
             ret, frame = cap.read()
             if ret == False:
                  break
             frame = cv2.flip(frame,1)  #espejo a la camara 
             heigth, width, _ = frame.shape 
             frame_rgb= cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
             results = pose.process(frame_rgb)

             if results.pose_landmarks is not None:
               print(int(results.pose_landmarks.landmark[mp_pose.PoseLandmark.RIGHT_SHOULDER].z)) #saca la coordenada del hombro derecho, medida en cm se multiplica por el ancho para sacar la medida en pixeles 
               x11= int(results.pose_landmarks.landmark[11].x * width)
               y11 = int(results.pose_landmarks.landmark[11].y * heigth)

               x12= int(results.pose_landmarks.landmark[12].x * width)
               y12= int(results.pose_landmarks.landmark[12].y * heigth)

               x13= int(results.pose_landmarks.landmark[13].x * width)
               y13 = int(results.pose_landmarks.landmark[13].y * heigth)

               x14= int(results.pose_landmarks.landmark[14].x * width)
               y14 = int(results.pose_landmarks.landmark[14].y * heigth)

               x15= int(results.pose_landmarks.landmark[15].x * width)
               y15 = int(results.pose_landmarks.landmark[15].y * heigth)

               x16= int(results.pose_landmarks.landmark[16].x * width)
               y16 = int(results.pose_landmarks.landmark[16].y * heigth)

               #x17= int(results.pose_landmarks.landmark[17].x * width)
               #y17= int(results.pose_landmarks.landmark[17].y * height)

               #x18= int(results.pose_landmarks.landmark[18].x * width)
               #y18= int(results.pose_landmarks.landmark[18].y * height)

               #x19= int(results.pose_landmarks.landmark[19].x * width)
               #y19= int(results.pose_landmarks.landmark[19].y * height)

               #x20= int(results.pose_landmarks.landmark[20].x * width)
               #y20= int(results.pose_landmarks.landmark[20].y * height)

               #x21= int(results.pose_landmarks.landmark[21].x * width)
               #y21= int(results.pose_landmarks.landmark[21].y * height)

               #x22= int(results.pose_landmarks.landmark[22].x * width)
               #y22= int(results.pose_landmarks.landmark[22].y * height)

               x23= int(results.pose_landmarks.landmark[23].x * width)
               y23= int(results.pose_landmarks.landmark[23].y * heigth)

               x24= int(results.pose_landmarks.landmark[24].x * width)
               y24= int(results.pose_landmarks.landmark[24].y * heigth)

               x25= int(results.pose_landmarks.landmark[25].x * width)
               y25= int(results.pose_landmarks.landmark[25].y * heigth)

               x26= int(results.pose_landmarks.landmark[26].x * width)
               y26= int(results.pose_landmarks.landmark[26].y * heigth)

               x27= int(results.pose_landmarks.landmark[27].x * width)
               y27 = int(results.pose_landmarks.landmark[27].y * heigth)

               x28= int(results.pose_landmarks.landmark[28].x * width)
               y28= int(results.pose_landmarks.landmark[28].y * heigth)

               puntuacion = list()

               






               
               print (x24, y24, x26 , y26, x23, y23, x25, y25, x27, y27)
               cv2.line(frame, ( x11, y11), (x12 , y12), (255 , 255 , 255), 3) #unión de punto xy1 con xy2
               cv2.line(frame, ( x11, y11), (x13 , y13), (255 , 255 , 255), 3)
               cv2.line(frame, ( x11, y11), (x23 , y23), (255 , 255 , 255), 3) #unión de punto xy2 con xy3
               cv2.line(frame, ( x13, y13), (x15 , y15), (255 , 255 , 255), 3) 
               cv2.line(frame, ( x12, y12), (x14 , y14), (255 , 255 , 255), 3)
               cv2.line(frame, ( x14, y14), (x16 , y16), (255 , 255 , 255), 3) 
               cv2.line(frame, ( x12, y12), (x24 , y24), (255 , 255 , 255), 3)
               cv2.line(frame, ( x24, y24), (x26 , y26), (255 , 255 , 255), 3) 
               cv2.line(frame, ( x24, y24), (x23 , y23), (255 , 255 , 255), 3)
               cv2.line(frame, ( x26, y26), (x28 , y28), (255 , 255 , 255), 3) 
               cv2.line(frame, ( x23, y23), (x25 , y25), (255 , 255 , 255), 3)
               cv2.line(frame, ( x25, y25), (x27 , y27), (255 , 255 , 255), 3) 
               


               cv2.circle(frame,(x11, y11), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x12, y12), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x13, y13), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x15, y15), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x14, y14), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x16, y16), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x24, y24), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x26, y26), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x28, y28), 6, (43,214,38), -1) #color verde
               cv2.circle(frame,(x23, y23), 6, (43,214,38), -1) #color azul corrdenadas según indice del dibujo
               cv2.circle(frame,(x25, y25), 6, (43,214,38), -1) #color azul corrdenadas según indice del dibujo
               cv2.circle(frame,(x27, y27), 6, (43,214,38), -1)

               if  y24 >= y26-30 and y24 <=y26+30 and y23 >= y25-30 and y23 <=y25+30  :
                    cv2.line(frame, ( x24, y24), (x26 , y26), (0 , 255 , 255), 3) #unión de punto xy1 con xy2
                    cv2.line(frame, ( x23, y23), (x25 , y25), (0 , 255 , 255), 3) #unión de punto xy1 con xy2
                              
                    puntos = 2
                    puntuacion.append(puntos)
                    print (f" puntuación: {sum(puntuacion)} ")

               if sum(puntuacion) >= 2 :

                    font = cv2.FONT_HERSHEY_SIMPLEX

                    cv2.putText(img = frame, 
                                                       text = "GOOD JOB",
                                                       org = (200, 200),
                                                       fontFace = font,
                                                       fontScale = 2,
                                                       color = (255, 255, 255),
                                                       thickness = 2,
                                                       lineType = cv2.LINE_AA)

                    plt.imshow(frame)
                    plt.show()


          
             
               cv2.imshow("Frame", frame)
               if cv2.waitKey(1) & 0xFF == 27:
                    break
             
cap.release()
cv2.destroyAllWindows()

In [9]:
import cv2

# Crear un objeto de captura de video para la cámara (índice 0 para la primera cámara)
cap = cv2.VideoCapture(0)

# Verificar si la cámara se abrió correctamente
if not cap.isOpened():
    print("No se puede abrir la cámara")
    exit()

while True:
    # Capturar fotograma por fotograma
    ret, frame = cap.read()
    print (type(frame))
    # Si se lee correctamente 'ret' será True
    if not ret:
        print("No se puede recibir el fotograma (se alcanzó el final del video?). Saliendo ...")
        break
    
    # Operaciones en el fotograma
    #frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    
    # Mostrar el fotograma resultante
    cv2.imshow('frame', frame)
    
    if cv2.waitKey(1) == ord('q'):
        break

# Cuando todo esté listo, liberar la captura
cap.release()
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.nd

In [1]:
import sys
import cv2
import numpy as np
import mediapipe as mp
import matplotlib.pyplot as plt

sys.path.append('..')
import utils 
from FSM_squat import FSM_squat
from thresholds import get_thresholds

mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose

cap = cv2.VideoCapture(0)
FSM = FSM_squat(get_thresholds())
puntuacion= list()
with mp_pose.Pose(
    static_image_mode=False) as pose:   #PARA VIDEOS PONER FALSE /TRUE ES PARA FOTOS
        while True:
            ret, frame = cap.read()
            print(frame)
                    
            
            #print (ret)
            #frame_rgb= cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
            FSM_squat.process(FSM, frame, pose)
            #frame = cv2.flip(frame,1)  #espejo a la camara 
            #heigth, width, _ = frame.shape 
            
            #results = pose.process(frame_rgb)

            #if results.pose_landmarks is not None:
            cv2.imshow("Frame", frame)
            if cv2.waitKey(1) & 0xFF == 27:
                break
             
cap.release()
cv2.destroyAllWindows()

2024-08-01 13:31:52.528341: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-01 13:31:56.743 python[31037:11824361] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[ 53  45  89]
  [ 54  46  90]
  [ 56  47  91]
  ...
  [ 11  52  95]
  [ 20  61 104]
  [ 18  60 103]]

 [[ 53  45  89]
  [ 54  46  90]
  [ 55  47  91]
  ...
  [ 13  54  97]
  [ 19  61 104]
  [ 16  59 102]]

 [[ 51  45  89]
  [ 53  46  90]
  [ 54  47  91]
  ...
  [ 15  57 100]
  [ 18  61 104]
  [ 15  59 102]]

 ...

 [[ 37  38  60]
  [ 31  33  55]
  [ 23  24  47]
  ...
  [ 71  97 147]
  [ 69  95 144]
  [ 66  92 142]]

 [[ 31  33  54]
  [ 29  31  51]
  [ 24  26  47]
  ...
  [ 72  99 147]
  [ 71  97 146]
  [ 68  95 144]]

 [[ 26  29  49]
  [ 26  29  49]
  [ 25  28  47]
  ...
  [ 73

In [1]:
int(int(5))

5